[features]
seeds = false
skip-lint = false
[programs.localnet]
nft_minter = "3u2FbbGTHow99DujYPjHEGxujQ1Mtw6DjukWDe2hYpHp"
nft_shop = "7pXnhhAyw8HCwWPHEYy3nwhdFCc4nQBWVAgQGTBPAoDe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
